version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_DATABASE: nest-pokemon
    env_file:
      - .env
    volumes:
      - ./mongo:/data/db
